version: '3'

services:
  neo_src:
    image: neo4j:4.2.0
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ../storage/neo_src:/data
    environment:
      NEO4j_dbms.memory.pagecache.size: ${NEO_PAGESIZE}
      NEO4J_AUTH: ${NEOSRC_NEO4J_AUTH}
#      NEO4JLABS_PLUGINS: '["n10s"]'
    deploy:
      resources:
        limits:
          memory: "${MAX_NEO_RAM}"

  neo_dest:
    image: neo4j:4.2.0
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ../storage/neo_dest:/data
    environment:
      NEO4j_dbms.memory.pagecache.size: ${NEO_PAGESIZE}
      NEO4J_AUTH: ${NEODEST_NEO4J_AUTH}
    deploy:
      resources:
        limits:
          memory: "${MAX_NEO_RAM}"

  redis:
    image: redis:6.0
    user: ${UID:-1000}:${GID:-1000}
    command: 'redis-server --appendonly yes'
    deploy:
      resources:
        limits:
          memory: "${MAX_REDIS_RAM}"
    volumes:
      - ../storage/redis:/data

  app:
    build: ./docker/python
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ./:/app
      - ../resources_disambiguation:/data
    deploy:
      resources:
        limits:
          memory: "${MAX_APP_RAM}"
    environment:
      - PM2_PROC_NUM
      - APP_MODE

