version: '3'

services:
  neo_src:
    image: neo4j:4.2.0
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ../storage/neo_src:/data
    environment:
      NEO4J_AUTH: ${NEOSRC_NEO4J_AUTH}
    deploy:
      resources:
        limits:
          memory: "${MAX_NEO_RAM}"

  neo_dest:
    image: neo4j:4.2.0
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ../storage/neo_dest:/data
    environment:
      NEO4J_AUTH: ${NEODEST_NEO4J_AUTH}
    deploy:
      resources:
        limits:
          memory: "${MAX_NEO_RAM}"

  redis:
    image: redis:6.0
    user: ${UID:-1000}:${GID:-1000}
    command: 'redis-server --appendonly yes'
    volumes:
      - ../storage/redis:/data

#  wcrft:
#    user: root
#    build: ./docker/wcrft
#    image: clarinpl/cpp
#    environment:
#      - SSH_PUBLICKEY

  app:
    build: ./docker/python
    volumes:
      - ./:/app
    environment:
      - SSH_PRIVATEKEY
      - SSH_PUBLICKEY
      - PM2_PROC_NUM
      - APP_MODE

